### ISSUE TITLE
Update to 1.21.4 Please

### ISSUE THREAD

**Issue by sternschnaube** [marie0llie/themetip#3]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'themetip'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at me.replet.client.ModLoaders.fabricEntrypoints(ModLoaders.java:7)
	at net.minecraft.class_310.redirect$heo000$vanillafix$catchFabricInit(class_310.java:32228)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalAccessError: class gay.marie_the.themetip.Themetip tried to access private method 'void net.minecraft.class_2960.<init>(java.lang.String, java.lang.String)' (gay.marie_the.themetip.Themetip and net.minecraft.class_2960 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @69b794e2)
	at gay.marie_the.themetip.Themetip.id(Themetip.java:22)
	at gay.marie_the.themetip.config.ThemetipConfig.<clinit>(ThemetipConfig.java:69)
	at gay.marie_the.themetip.Themetip.onInitialize(Themetip.java:16)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 8 more

**Comment by venaminecraft** [comment]
Please update @3drosalia, it's one of my favourite mods out there 😊
